name: Sentinel Workflow
on: [push, pull_request_target]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Poetry install
        run: poetry install

      - name: Run Unit tests
        run: |
          poetry run coverage run -m pytest tests/test_unit.py
          poetry run coverage report --fail-under 90

      - name: Prewarm
        run: curl --silent https://sentim-api.herokuapp.com >/dev/null

      - name: Run integration tests
        run: poetry run pytest tests/test_integration.py

      - name: Deploy to develop and run regression tests
        uses: ./.github/actions/deploy-heroku
        if: github.ref_name != 'main' || github.event_name == 'pull_request_target'
        with:
          secret: ${{ secrets.HEROKU_API_KEY }}
          app: sentineldev
          email: samo@jelovsek.net

      - name: Deploy to production and run regression tests
        uses: ./.github/actions/deploy-heroku
        if: github.ref_name == 'main' && github.event_name == 'push'
        with:
          secret: ${{ secrets.HEROKU_API_KEY }}
          app: sentinelprod
          email: samo@jelovsek.net
